# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

linters:
  # enables all defaults + the below, `golangci-lint linters` to see the list of active linters.
  enable:
    - gofmt
    - godot
    - govet
    - stylecheck
    - goconst
    - prealloc
    - unparam
  disable:
    - typecheck

linters-settings:
  gofmt:
    simplify: true

run:
  timeout: 5m
